language: node_js
os: osx
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_script:
  - npm install