language: node_js
node_js:
  - "iojs"
  - "node"
  - "8"
  - "4"
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script: npm test
before_script:
  - npm install
cache:
  directories:
    - node_modules
