language: node_js
node_js: 
    - iojs
    - 8
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_script:
  - npm install
cache:
  directories:
    - node_modules